### PR TITLE
chore: move .storybook config folder to packages/storybook

### PR DESCRIPTION
**Pull request by chanar**

### CODE REVIEW

**Comment by lkraav** [comment]
@chanar no info on why this is better?

**Comment by chanar** [comment]
@lkraav commented on gitter. 

"I moved .storybook config folder to packages/storybook to simplify dependency management".

**Comment by lkraav** [comment]
Indeed, it's just not obvious to a noob like me how did it become simpler.

**Comment by web-padawan** [comment]
I was thinking about putting all the Storybook stuff into its package, so definitely 👍

**Comment by lkraav** [comment]
Right. I wasn't sure if the current toolchain setup somehow required `.storybook` sit at root, etc

**Pull request merged**
