### PR TITLE
chore: update sass render script to work faster

### PR DESCRIPTION
**Pull request by web-padawan**

### CODE REVIEW

**Comment by lkraav** [comment]
@web-padawan should I migrate my QA findings here, or you are picking them up from #15

**Comment by web-padawan** [comment]
@lkraav this PR is a copy of #17 and I now when it passed I will go ahead and merge it.
Let's continue sass-render discussion in #15 if you wish, or submit another PR.

**Comment by lkraav** [comment]
Oooh, I meant "picking them up from #17"

**Comment by web-padawan** [comment]
Agree about https://github.com/web-padawan/aybolit/pull/17#issuecomment-481740093
I will tweak this PR to exclude these internal files starting with `_`

**Comment by lkraav** [comment]
Also, info message about generated target output would be nice.

**Comment by web-padawan** [comment]
Updated the code and moved `sass-render` to separate package, also fixed few lint errors.

**Comment by lkraav** [comment]
@web-padawan maybe line capitalization was left a little bit inconsistent for messages. All sentence-case, perhaps?

```
/usr/bin/node /usr/lib/node_modules/yarn/bin/yarn.js run watch
yarn run v1.15.2
$ node scripts/watcher.js
watcher started!
saw change to packages/core/scss/button-base.scss
building styles
Processing packages/core/scss/button-base.scss

watcher build complete!
```

**Comment by web-padawan** [comment]
Sure, I will update it. Thanks, also noticed that yesterday while trying watcher.

**Pull request merged**
